openapi: 3.0.1
info:
  title: AfrasiaTestAccountAPI
  description: API Definition of AfrasiaTestAccountAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/afrasia/bank/1.0.0
paths:
  /accounts/test:
    get:
      responses:
        default:
          description: Default response
  /accounts/{accountType}:
    get:
      parameters:
      - name: accountType
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
